table DimEspecialidades
	lineageTag: 6cd415ce-ffa5-4e2d-a0d7-0cef3b5c2c2e

	column Especialidade
		dataType: string
		lineageTag: 4a10f6be-620a-497f-b624-77de52b72656
		summarizeBy: none
		sourceColumn: Especialidade

		annotation SummarizationSetBy = Automatic

	column EspecialidadeCurta =
			IF(
			    LEN([Especialidade]) <= 26,
			    [Especialidade],
			    LEFT([Especialidade], 23) & "..."
			)
		dataType: string
		lineageTag: f3a68b50-4f1c-4be9-b7f6-2f4bd8a6886b
		summarizeBy: none

		annotation SummarizationSetBy = User

	partition DimEspecialidades = m
		mode: import
		source =
				let
				    Source = FactPericias,
				
				    NormalizeLabel = (value as any) as nullable text =>
				        let
				            Base = fnNormalizeText(value),
				            Trimmed = if Base = null then null else Text.Trim(Base),
				            Canonical = if Trimmed = null or Trimmed = "" then null else Text.Proper(Text.Lower(Trimmed)),
				            UpperValue = if Canonical = null then null else Text.Upper(Canonical)
				        in
				            if UpperValue = null or UpperValue = "" or UpperValue = "SEM INFO" then null
				            else if Text.StartsWith(UpperValue, "SEM ") then null
				            else Canonical,
				
				    StripAccents = (textValue as nullable text) as nullable text =>
				        if textValue = null then
				            null
				        else
				            let
				                Replacements = {
				                    {"├ü", "A"}, {"├Ç", "A"}, {"├é", "A"}, {"├â", "A"}, {"├ä", "A"},
				                    {"├í", "a"}, {"├á", "a"}, {"├ó", "a"}, {"├ú", "a"}, {"├Ą", "a"},
				                    {"├ë", "E"}, {"├ł", "E"}, {"├Ő", "E"}, {"├ő", "E"},
				                    {"├ę", "e"}, {"├Ę", "e"}, {"├¬", "e"}, {"├ź", "e"},
				                    {"├Ź", "I"}, {"├î", "I"}, {"├Ä", "I"}, {"├Ć", "I"},
				                    {"├ş", "i"}, {"├Č", "i"}, {"├«", "i"}, {"├»", "i"},
				                    {"├ô", "O"}, {"├ĺ", "O"}, {"├ö", "O"}, {"├Ľ", "O"}, {"├ľ", "O"},
				                    {"├│", "o"}, {"├▓", "o"}, {"├┤", "o"}, {"├Á", "o"}, {"├Â", "o"},
				                    {"├Ü", "U"}, {"├Ö", "U"}, {"├Ť", "U"}, {"├ť", "U"},
				                    {"├║", "u"}, {"├╣", "u"}, {"├╗", "u"}, {"├╝", "u"},
				                    {"├ç", "C"}, {"├ž", "c"},
				                    {"├Ĺ", "N"}, {"├▒", "n"}
				                },
				                Stripped = List.Accumulate(Replacements, textValue, (state as text, pair as list) => Text.Replace(state, pair{0}, pair{1}))
				            in
				                Stripped,
				
				    BuildKey = (textValue as nullable text) as nullable text =>
				        if textValue = null then
				            null
				        else
				            let
				                Upper = Text.Upper(StripAccents(textValue)),
				                KeptChars = Text.Select(Upper, List.Combine({{"A".."Z"}, {"0".."9"}, {" "}})),
				                Parts = List.Select(Text.Split(Text.Trim(KeptChars), " "), each _ <> ""),
				                Key = if List.Count(Parts) = 0 then null else Text.Combine(Parts, " ")
				            in
				                Key,
				
				    KeepColumns = Table.SelectColumns(Source, {"Especialidade"}, MissingField.UseNull),
				    Cleaned = Table.TransformColumns(KeepColumns, {{"Especialidade", each NormalizeLabel(_), type nullable text}}),
				    WithKey = Table.AddColumn(Cleaned, "EspecialidadeKey", each BuildKey([Especialidade]), type nullable text),
				    RemoveNullOrBlank = Table.SelectRows(WithKey, each [EspecialidadeKey] <> null and Text.Trim([EspecialidadeKey]) <> ""),
				    Grouped = Table.Group(RemoveNullOrBlank, {"EspecialidadeKey"}, {{"Especialidade", each List.Min(List.RemoveNulls([Especialidade])), type nullable text}}),
				    Result = Table.SelectColumns(Grouped, {"Especialidade"}),
				    DistinctEspecialidades = Table.Distinct(Result, {"Especialidade"}),
				    Sorted = Table.Sort(DistinctEspecialidades, {{"Especialidade", Order.Ascending}})
				in
				    Sorted

	annotation PBI_NavigationStepName = Navega├ž├úo

	annotation PBI_ResultType = Table

