table FactPericias
	lineageTag: 5236453a-0009-44f5-95b4-6a46c5c9dc10

	measure 'Qtd Perícias' = COUNTROWS(FactPericias)
		formatString: #,0
		lineageTag: f05aebd2-5b00-4ecd-bb6f-54df3eb19625

	measure 'Valor Arbitrado' = SUM(FactPericias[ValorArbitrado])
		formatString: R$ #,##0.00;R$ -#,##0.00;R$ 0.00
		lineageTag: ae18ea0b-2f7b-45a0-bad8-9750d5149b52

	measure 'Valor Adiantado Efetivo' = SUM(FactPericias[ValorAdiantadoEfetivo])
		formatString: R$ #,##0.00;R$ -#,##0.00;R$ 0.00
		isHidden
		lineageTag: 59db0e32-0318-4ddf-b1cf-68714d88b18b

	measure 'Saldo a Receber' = SUM(FactPericias[SaldoCalculado])
		formatString: R$ #,##0.00;R$ -#,##0.00;R$ 0.00
		lineageTag: 2caac1ba-8976-4277-a822-19001a4cc71f

	measure 'Perícias com Autorização' = CALCULATE([Qtd Perícias], FactPericias[HasAutorizacao] = TRUE())
		formatString: #,0
		isHidden
		lineageTag: 6953b6a1-9e3b-4fbe-935a-756c768bb235

	measure 'Peritos Distintos' =
			CALCULATE(
				DISTINCTCOUNT(FactPericias[PeritoKey]),
				FactPericias[PeritoKey] <> "NOME|SEM PERITO"
			)
		formatString: #,0
		lineageTag: 3268e836-a3c1-46f1-b5b6-99ea1f84ed9b

	measure 'Especialidades Distintas' =
			CALCULATE(
				DISTINCTCOUNT(FactPericias[Especialidade]),
				FactPericias[Especialidade] <> "SEM ESPECIALIDADE"
			)
		formatString: #,0
		lineageTag: f563909d-cd53-4f0f-b130-008245beea42

	measure 'Valor Médio por Perícia' = DIVIDE([Valor Arbitrado], [Qtd Perícias])
		formatString: R$ #,##0.00;R$ -#,##0.00;R$ 0.00
		lineageTag: 9f0bbf7d-7831-4284-b478-0f71f5e85605

	measure 'Saldo Médio por Perícia' = DIVIDE([Saldo a Receber], [Qtd Perícias])
		formatString: R$ #,##0.00;R$ -#,##0.00;R$ 0.00
		lineageTag: bb856ecd-2188-478f-8ce6-1f1e7778ec92

	measure 'Backlog (Qtd pendente)' = CALCULATE([Qtd Perícias], FactPericias[StatusFluxo] <> "Com Adiantamento")
		formatString: #,0
		lineageTag: 63f7d45e-8382-49ce-b0f5-e676f381f5ca

	measure 'Backlog (Saldo pendente)' = CALCULATE([Saldo a Receber], FactPericias[StatusFluxo] <> "Com Adiantamento")
		formatString: R$ #,##0.00;R$ -#,##0.00;R$ 0.00
		lineageTag: 9626f02c-7a02-4f26-bd32-27b3f5d33b6d

	measure 'Ticket Médio' = DIVIDE([Valor Arbitrado], [Qtd Perícias])
		formatString: R$ #,##0.00;R$ -#,##0.00;R$ 0.00
		lineageTag: 4d9adfca-8f00-4c53-b5d4-3ebf3e5adf9f

	measure 'Participação %' =
			DIVIDE(
				[Valor Arbitrado],
				CALCULATE(
					[Valor Arbitrado],
					ALLSELECTED(DimComarcas),
					ALLSELECTED(DimVaras),
					ALLSELECTED(DimEspecialidades),
					ALLSELECTED(DimPeritos)
				)
			)
		formatString: 0.00%
		lineageTag: 284818cc-b43f-4f1c-acf9-c67f86cf5ace

	measure 'Top 10 Peritos (Valor)' =
			CALCULATE(
				[Valor Arbitrado],
				TOPN(
					10,
					ALLSELECTED(DimPeritos[PeritoLabel]),
					[Valor Arbitrado],
					DESC
				)
			)
		formatString: R$ #,##0.00;R$ -#,##0.00;R$ 0.00
		lineageTag: 2f9a8a56-33f3-4cb6-a0ad-9fef62908718

	measure 'Participação Top 10 Peritos %' = DIVIDE([Top 10 Peritos (Valor)], [Valor Arbitrado])
		formatString: 0.00%
		lineageTag: 0ec90ad2-44bf-4693-8ad5-c914a2003cd1

	measure 'Linhas SEM PERITO' = CALCULATE(COUNTROWS(FactPericias), FactPericias[PeritoLabel] = "SEM PERITO")
		formatString: #,0
		lineageTag: a571c509-58a4-47d5-939d-f3d4f11f80be

	measure 'Linhas SEM COMARCA' = CALCULATE(COUNTROWS(FactPericias), FactPericias[Comarca] = "SEM COMARCA")
		formatString: #,0
		lineageTag: bfd3b25a-b810-4f72-a9b5-a97f568dc6dd

	measure 'Linhas Valor Arbitrado Nulo/Zero' =
			CALCULATE(
				COUNTROWS(FactPericias),
				FILTER(
					FactPericias,
					ISBLANK(FactPericias[ValorArbitrado]) || FactPericias[ValorArbitrado] <= 0
				)
			)
		formatString: #,0
		lineageTag: b615f60d-76ac-4130-b4ea-f07fcf41bc4c

	measure 'Comarca Selecionada' = SELECTEDVALUE(DimComarcas[Comarca], "Todas as comarcas")
		lineageTag: 2fd9b08f-9c38-4f6f-9fd1-a929f6624e8f

	measure 'Peritos na Comarca' =
			CALCULATE(
				DISTINCTCOUNT(FactPericias[PeritoKey]),
				FactPericias[PeritoKey] <> "NOME|SEM PERITO"
			)
		formatString: #,0
		lineageTag: 5f52e7b2-2d62-4ead-9a89-09704a34fb68

	measure 'Varas na Comarca' = DISTINCTCOUNT(FactPericias[Juizo])
		formatString: #,0
		lineageTag: 6a774a2f-1019-4fb5-9eb4-f248258b41d6

	measure 'Especialidades na Comarca' = DISTINCTCOUNT(FactPericias[Especialidade])
		formatString: #,0
		lineageTag: d9a8df12-39f5-4f05-b8d2-b0c4f3ecf781

	measure 'Quem Recebe Mais (Valor)' =
			VAR TopPerito =
				TOPN(
					1,
					SUMMARIZE(
						FILTER(FactPericias, FactPericias[PeritoLabel] <> "SEM PERITO"),
						FactPericias[PeritoLabel],
						"ValorPerito", [Valor Arbitrado]
					),
					[ValorPerito], DESC,
					FactPericias[PeritoLabel], ASC
				)
			RETURN
				MAXX(TopPerito, [ValorPerito])
		formatString: R$ #,##0.00;R$ -#,##0.00;R$ 0.00
		lineageTag: fd72f5ee-4e46-4df8-b31f-9f6e63d4153e

	measure 'Campeão da Comarca' =
			VAR TopPerito =
				TOPN(
					1,
					SUMMARIZE(
						FILTER(FactPericias, FactPericias[PeritoLabel] <> "SEM PERITO"),
						FactPericias[PeritoLabel],
						"ValorPerito", [Valor Arbitrado]
					),
					[ValorPerito], DESC,
					FactPericias[PeritoLabel], ASC
				)
			VAR Nome = MAXX(TopPerito, FactPericias[PeritoLabel])
			VAR Valor = MAXX(TopPerito, [ValorPerito])
			RETURN
				IF(ISBLANK(Valor), BLANK(), Nome & " | " & FORMAT(Valor, "R$ #,##0.00"))
		lineageTag: f73cfd80-8f5e-4f74-a14e-b5b3bf315151

	measure 'Vara Campeã (Comarca)' =
			VAR TopVara =
				TOPN(
					1,
					SUMMARIZE(
						FactPericias,
						FactPericias[JuizoExibicao],
						"ValorVara", [Valor Arbitrado]
					),
					[ValorVara], DESC,
					FactPericias[JuizoExibicao], ASC
				)
			RETURN
				MAXX(TopVara, FactPericias[JuizoExibicao])
		lineageTag: 81280988-1aaf-44ad-bf0e-5093898bc068

	measure 'Especialidades Top 5 (Comarca)' =
			VAR TopEsp =
				TOPN(
					5,
					SUMMARIZE(
						FactPericias,
						FactPericias[EspecialidadeExibicao],
						"ValorEsp", [Valor Arbitrado]
					),
					[ValorEsp], DESC,
					FactPericias[EspecialidadeExibicao], ASC
				)
			RETURN
				CONCATENATEX(TopEsp, FactPericias[EspecialidadeExibicao], ", ")
		lineageTag: c4df74de-6524-4007-be8e-f12f9b40d422

	measure 'Peritos Top 5 (Comarca)' =
			VAR TopPeritos =
				TOPN(
					5,
					SUMMARIZE(
						FILTER(FactPericias, FactPericias[PeritoLabel] <> "SEM PERITO"),
						FactPericias[PeritoLabel],
						"ValorPerito", [Valor Arbitrado]
					),
					[ValorPerito], DESC,
					FactPericias[PeritoLabel], ASC
				)
			RETURN
				CONCATENATEX(TopPeritos, FactPericias[PeritoLabel], ", ")
		lineageTag: 89c64f51-7ca8-4e51-8091-2e2743f4d1ce

	column PeritoNome
		dataType: string
		isHidden
		lineageTag: 86cc9324-23b4-4d1f-892d-79a941b786de
		summarizeBy: none
		sourceColumn: PeritoNome

		annotation SummarizationSetBy = Automatic

	column EspeciePericia
		dataType: string
		isHidden
		lineageTag: c527351f-48c7-4eae-94e9-64edae50e18e
		summarizeBy: none
		sourceColumn: EspeciePericia

		annotation SummarizationSetBy = Automatic

	column Fator
		dataType: double
		lineageTag: db766081-8acb-4397-bd80-dae86fad3513
		summarizeBy: sum
		sourceColumn: Fator

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NumeroPericia
		dataType: string
		isHidden
		lineageTag: d7fbf50b-8eaa-4571-808e-bd26cdd65b42
		summarizeBy: none
		sourceColumn: NumeroPericia

		annotation SummarizationSetBy = Automatic

	column DataRequisicao
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6e4892a6-4854-451e-9395-a48ce939de81
		summarizeBy: none
		sourceColumn: DataRequisicao

		variation Variation
			isDefault
			relationship: c802f80b-7603-42b4-88bf-17c7c604e54a
			defaultHierarchy: LocalDateTable_80d6bfdd-4f21-4567-b3a6-8617d8845fde.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProcessoAdminNumero
		dataType: string
		lineageTag: 9b27c194-9d1c-4162-887c-93d23a316b2a
		summarizeBy: none
		sourceColumn: ProcessoAdminNumero

		annotation SummarizationSetBy = Automatic

	column Juizo
		dataType: string
		isHidden
		lineageTag: 5dade012-ac69-4e7b-94b5-2c645316d221
		summarizeBy: none
		sourceColumn: Juizo

		annotation SummarizationSetBy = Automatic

	column Comarca
		dataType: string
		isHidden
		lineageTag: 816328e1-9813-4139-8c7b-709bbee6355e
		summarizeBy: none
		sourceColumn: Comarca

		annotation SummarizationSetBy = Automatic

	column ProcessoNumero
		dataType: string
		lineageTag: efc80a97-d174-497d-a885-e584ed82aaac
		summarizeBy: none
		sourceColumn: ProcessoNumero

		annotation SummarizationSetBy = Automatic

	column Promovente
		dataType: string
		lineageTag: 0376008d-09b2-4da0-9452-d2ae418fe534
		summarizeBy: none
		sourceColumn: Promovente

		annotation SummarizationSetBy = Automatic

	column Promovido
		dataType: string
		lineageTag: 63eb7a2f-3757-46af-8464-4f34dfe7c96f
		summarizeBy: none
		sourceColumn: Promovido

		annotation SummarizationSetBy = Automatic

	column Especialidade
		dataType: string
		isHidden
		lineageTag: 1ea4b4d2-05c3-4cb1-b5d9-3d74463d1491
		summarizeBy: none
		sourceColumn: Especialidade

		annotation SummarizationSetBy = Automatic

	column ValorTabelado
		dataType: double
		lineageTag: 1978e8d1-c12d-4803-9d93-029c664635ed
		summarizeBy: sum
		sourceColumn: ValorTabelado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ValorArbitrado
		dataType: double
		lineageTag: c051a34d-c36c-40bf-9a2c-258eea0bc731
		summarizeBy: sum
		sourceColumn: ValorArbitrado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Checagem
		dataType: string
		lineageTag: 931c2797-065f-43c2-a159-53a693efac77
		summarizeBy: none
		sourceColumn: Checagem

		annotation SummarizationSetBy = Automatic

	column DataAdiantamento
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 075e34bb-3c29-4721-aa67-5e3822f25348
		summarizeBy: none
		sourceColumn: DataAdiantamento

		variation Variation
			isDefault
			relationship: 12eca357-65f9-4d3f-a412-af8ccb8fd484
			defaultHierarchy: LocalDateTable_76cc1d11-5866-4430-bacd-bf62edb5aae0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ValorAdiantado
		dataType: double
		isHidden
		lineageTag: 05da38bc-ff40-416a-b089-e178edb7e60d
		summarizeBy: sum
		sourceColumn: ValorAdiantado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PercentualAdiantado
		dataType: double
		isHidden
		lineageTag: a740d509-de0d-4c55-8f0c-4310f6201a87
		summarizeBy: sum
		sourceColumn: PercentualAdiantado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ChecagemAdiantamento
		dataType: string
		isHidden
		lineageTag: 580cc968-4d08-48bf-b971-1bf956e322b5
		summarizeBy: none
		sourceColumn: ChecagemAdiantamento

		annotation SummarizationSetBy = Automatic

	column DataAutorizacaoDespesa
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: b0eaa04c-2b5d-4407-941f-040a36248ccd
		summarizeBy: none
		sourceColumn: DataAutorizacaoDespesa

		variation Variation
			isDefault
			relationship: 707f69bb-70d0-4996-bea1-32cc85dab41e
			defaultHierarchy: LocalDateTable_ee889c8e-afcf-4150-8321-4984f89ba935.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SaldoAReceber
		dataType: double
		lineageTag: eab7c77c-048e-467e-9325-4eb8ecfd553b
		summarizeBy: sum
		sourceColumn: SaldoAReceber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SaldoFinal
		dataType: double
		lineageTag: 0dd8942c-eafa-4250-bbaf-5cf0a9cf2a2f
		summarizeBy: sum
		sourceColumn: SaldoFinal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CpfCnpjDigits
		dataType: string
		isHidden
		lineageTag: ee84a818-86ab-40c9-a4ee-0d1ae8358b54
		summarizeBy: none
		sourceColumn: CpfCnpjDigits

		annotation SummarizationSetBy = Automatic

	column CpfCnpjMascarado
		dataType: string
		isHidden
		lineageTag: 54edebd0-d2c8-4758-87f4-adf41718cc5d
		summarizeBy: none
		sourceColumn: CpfCnpjMascarado

		annotation SummarizationSetBy = Automatic

	column HasAutorizacao
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 109ef917-2109-4d9b-8e05-311652d76acd
		summarizeBy: none
		sourceColumn: HasAutorizacao

		annotation SummarizationSetBy = Automatic

	column HasAdiantamento
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 48529135-0693-49fe-8bb6-61a265b28dce
		summarizeBy: none
		sourceColumn: HasAdiantamento

		annotation SummarizationSetBy = Automatic

	column ValorAdiantadoEfetivo
		dataType: double
		isHidden
		lineageTag: 517d0d51-82de-4137-ab3a-b3b24a1c166c
		summarizeBy: sum
		sourceColumn: ValorAdiantadoEfetivo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SaldoCalculado
		dataType: double
		lineageTag: 121d9bc4-bdf8-4e2f-99db-d8f655ff10cc
		summarizeBy: sum
		sourceColumn: SaldoCalculado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiasDesdeRequisicao
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3ba2a2bc-c28d-4150-9216-6106120c7c5d
		summarizeBy: sum
		sourceColumn: DiasDesdeRequisicao

		annotation SummarizationSetBy = Automatic

	column AgingFaixa
		dataType: string
		lineageTag: 5a33f312-0fdb-4c9c-a5cb-778a8afc0cf2
		summarizeBy: none
		sourceColumn: AgingFaixa

		annotation SummarizationSetBy = Automatic

	column DiasReqAteAutorizacao
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ec8040d9-c542-443c-b9e5-be219ee934e5
		summarizeBy: sum
		sourceColumn: DiasReqAteAutorizacao

		annotation SummarizationSetBy = Automatic

	column DiasAutAteAdiantamento
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 960813f4-2ad3-40a8-8319-a6d8c9d825b3
		summarizeBy: sum
		sourceColumn: DiasAutAteAdiantamento

		annotation SummarizationSetBy = Automatic

	column StatusFluxo
		dataType: string
		isHidden
		lineageTag: 78fabcaa-87fd-48e9-bc0f-f32fc58e6caa
		summarizeBy: none
		sourceColumn: StatusFluxo

		annotation SummarizationSetBy = Automatic

	column PeritoNomeExibicao
		dataType: string
		lineageTag: 9180be2f-ccd0-413a-bd3b-346c6664511e
		summarizeBy: none
		sourceColumn: PeritoNomeExibicao

		annotation SummarizationSetBy = Automatic

	column JuizoExibicao
		dataType: string
		lineageTag: 96eb7afd-9512-4795-ac73-1662d8b4c985
		summarizeBy: none
		sourceColumn: JuizoExibicao

		annotation SummarizationSetBy = Automatic

	column ComarcaExibicao
		dataType: string
		lineageTag: 105acce6-61c5-4adc-8bcd-2f8145ed22bc
		summarizeBy: none
		sourceColumn: ComarcaExibicao

		annotation SummarizationSetBy = Automatic

	column EspecialidadeExibicao
		dataType: string
		lineageTag: 3af6b4a1-a955-4e65-8300-1e7d5166548a
		summarizeBy: none
		sourceColumn: EspecialidadeExibicao

		annotation SummarizationSetBy = Automatic

	column PeritoKey
		dataType: string
		isHidden
		lineageTag: be63335b-7b73-4c2a-bcd4-ac3fa80e8028
		summarizeBy: none
		sourceColumn: PeritoKey

		annotation SummarizationSetBy = Automatic

	column NomeNorm
		dataType: string
		isHidden
		lineageTag: 243e5266-8a80-45d2-98f1-21e22ac2c40e
		summarizeBy: none
		sourceColumn: NomeNorm

		annotation SummarizationSetBy = Automatic

	column DocValid
		dataType: string
		isHidden
		lineageTag: 11b8910e-f7bc-40c5-8418-cd68c92e0fd1
		summarizeBy: none
		sourceColumn: DocValid

		annotation SummarizationSetBy = Automatic

	column DocFinal
		dataType: string
		isHidden
		lineageTag: 95a59731-1668-45cb-8162-f527fc8645a9
		summarizeBy: none
		sourceColumn: DocFinal

		annotation SummarizationSetBy = Automatic

	column QtdDocsDistintos
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ddd71b4a-fd60-4f60-a359-d10d4013301a
		summarizeBy: none
		sourceColumn: QtdDocsDistintos

		annotation SummarizationSetBy = Automatic

	column DocsMascaradosConcatenados
		dataType: string
		isHidden
		lineageTag: b043529b-650e-4c6b-9308-f1737613a3a7
		summarizeBy: none
		sourceColumn: DocsMascaradosConcatenados

		annotation SummarizationSetBy = Automatic

	column NomeComDocsMultiplos
		dataType: string
		isHidden
		lineageTag: b9f5a286-baf9-49f0-9da8-e9c5654ec029
		summarizeBy: none
		sourceColumn: NomeComDocsMultiplos

		annotation SummarizationSetBy = Automatic

	column PeritoLabel
		dataType: string
		isHidden
		lineageTag: a6eb389d-0f6b-4407-b428-94757ebce92a
		summarizeBy: none
		sourceColumn: PeritoLabel

		annotation SummarizationSetBy = Automatic

	partition FactPericias = m
		mode: import
		source =
				let
				    ExcelPath0 = try Text.From(ExcelPath) otherwise "",
				    ExcelPath1 = Text.Clean(Text.Trim(ExcelPath0)),
				    ExcelPath2 = Text.Replace(Text.Replace(ExcelPath1, Character.FromNumber(34), ""), "'", ""),
				    ExcelPathFinal = Text.Replace(ExcelPath2, "/", Character.FromNumber(92)),
				    SheetName0 = try Text.From(SheetName) otherwise "",
				    SheetName1 = Text.Clean(Text.Trim(SheetName0)),
				    SheetNameFinal = if SheetName1 = "" then "Dados (Tabela)" else SheetName1,
				
				    Source = Excel.Workbook(File.Contents(ExcelPathFinal), null, true),
				    RawData =
				        let
				            BySheet = try Source{[Item = SheetNameFinal, Kind = "Sheet"]}[Data] otherwise null,
				            ByTable = if BySheet <> null then null else (try Source{[Item = SheetNameFinal, Kind = "Table"]}[Data] otherwise null),
				            Fallback = if BySheet <> null then BySheet else if ByTable <> null then ByTable else Source{[Item = "Dados (Tabela)", Kind = "Sheet"]}[Data]
				        in
				            Fallback,
				
				    #"Skip Top Rows" = Table.Skip(RawData, 2),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Skip Top Rows", [PromoteAllScalars = true]),
				
				    #"Renamed Columns" =
				        Table.RenameColumns(
				            #"Promoted Headers",
				            {
				                {"Nº DE PERÍCIAS", "NumeroPericia"},
				                {"DATA DA REQUISIÇÃO", "DataRequisicao"},
				                {"PROCESSO ADMIN. Nº", "ProcessoAdminNumero"},
				                {"JUÍZO", "Juizo"},
				                {"COMARCA", "Comarca"},
				                {"PROCESSO Nº", "ProcessoNumero"},
				                {"PROMOVENTE", "Promovente"},
				                {"PROMOVIDO", "Promovido"},
				                {"PERITO", "PeritoNome"},
				                {"CPF/CNJP", "CpfCnpjRaw"},
				                {"CPF/CNPJ", "CpfCnpjRaw"},
				                {"ESPECIALIDADE", "Especialidade"},
				                {"ESPÉCIE DE PERÍCIA", "EspeciePericia"},
				                {"Fator", "Fator"},
				                {"Valor Tabelado Anexo I - Tabela I", "ValorTabelado"},
				                {"VALOR TABELADO", "ValorTabelado"},
				                {"VALOR ARBITRADO", "ValorArbitrado"},
				                {"CHECAGEM", "Checagem"},
				                {"DATA ADIANTAMENTO", "DataAdiantamento"},
				                {"R$", "ValorAdiantado"},
				                {"%", "PercentualAdiantado"},
				                {"CHECAGEM ADIATAMENTO", "ChecagemAdiantamento"},
				                {"CHECAGEM ADIANTAMENTO", "ChecagemAdiantamento"},
				                {"Data da Autorização da Despesa", "DataAutorizacaoDespesa"},
				                {"DATA DA AUTORIZAÇÃO DA DESPESA", "DataAutorizacaoDespesa"},
				                {"SALDO A RECEBER", "SaldoAReceber"},
				                {"SALDO FINAL", "SaldoFinal"}
				            },
				            MissingField.Ignore
				        ),
				
				    BaseCols = {
				        "NumeroPericia","DataRequisicao","ProcessoAdminNumero","Juizo","Comarca","ProcessoNumero",
				        "Promovente","Promovido","PeritoNome","CpfCnpjRaw","Especialidade","EspeciePericia",
				        "Fator","ValorTabelado","ValorArbitrado","Checagem","DataAdiantamento","ValorAdiantado","PercentualAdiantado",
				        "ChecagemAdiantamento","DataAutorizacaoDespesa","SaldoAReceber","SaldoFinal"
				    },
				    #"With All Base Cols" =
				        List.Accumulate(
				            BaseCols,
				            #"Renamed Columns",
				            (state as table, col as text) =>
				                if List.Contains(Table.ColumnNames(state), col) then state else Table.AddColumn(state, col, each null)
				        ),
				    #"Base Selected" = Table.SelectColumns(#"With All Base Cols", BaseCols, MissingField.UseNull),
				
				    ToText = (v as any) as nullable text =>
				        let t = if v = null then null else Text.Trim(Text.Clean(Text.From(v)))
				        in if t = "" then null else t,
				
				    ToDate = (v as any) as nullable date =>
				        let
				            d0 = try Date.From(v) otherwise null,
				            d1 =
				                if d0 <> null then d0
				                else
				                    let
				                        s0 = ToText(v),
				                        s1 = if s0 = null then null else Text.Replace(s0, "-", "/"),
				                        d2 = try Date.FromText(s1, "pt-BR") otherwise null
				                    in
				                        d2
				        in
				            d1,
				
				    ToNumber = (v as any) as nullable number =>
				        let
				            n0 = try Number.From(v) otherwise null,
				            n1 =
				                if n0 <> null then n0
				                else
				                    let
				                        s0 = ToText(v),
				                        s1 = if s0 = null then null else Text.Replace(Text.Replace(Text.Replace(Text.Replace(s0, "R$", ""), " ", ""), ".", ""), ",", "."),
				                        n2 = try Number.FromText(s1, "en-US") otherwise null
				                    in
				                        n2
				        in
				            n1,
				
				    ToPercentFraction = (v as any) as nullable number =>
				        let
				            n = ToNumber(v)
				        in
				            if n = null then null else if n > 1 then n / 100 else n,
				
				    NormalizeKey = (v as nullable text) as text =>
				        let
				            t0 = if v = null then "SEM PERITO" else Text.Upper(v),
				            t1 = Text.Select(t0, List.Combine({{"A".."Z"}, {"0".."9"}, {" "}})),
				            parts = List.Select(Text.Split(Text.Trim(t1), " "), each _ <> ""),
				            t2 = if List.Count(parts) = 0 then "SEM PERITO" else Text.Combine(parts, " ")
				        in
				            t2,
				
				    ToDisplay = (v as any, missingLabel as text) as text =>
				        let
				            t0 = ToText(v),
				            t1 = if t0 = null then missingLabel else t0,
				            u = Text.Upper(t1)
				        in
				            if Text.StartsWith(u, "SEM ") then u else Text.Proper(Text.Lower(t1)),
				
				    MaskDoc = (doc as nullable text) as nullable text =>
				        if doc = null or Text.Length(doc) < 4 then null else "******" & Text.End(doc, 4),
				
				    #"Text Cleaned" =
				        Table.TransformColumns(
				            #"Base Selected",
				            {
				                {"NumeroPericia", each ToText(_), type nullable text},
				                {"ProcessoAdminNumero", each ToText(_), type nullable text},
				                {"Juizo", each ToText(_), type nullable text},
				                {"Comarca", each ToText(_), type nullable text},
				                {"ProcessoNumero", each ToText(_), type nullable text},
				                {"Promovente", each ToText(_), type nullable text},
				                {"Promovido", each ToText(_), type nullable text},
				                {"PeritoNome", each ToText(_), type nullable text},
				                {"CpfCnpjRaw", each ToText(_), type nullable text},
				                {"Especialidade", each ToText(_), type nullable text},
				                {"EspeciePericia", each ToText(_), type nullable text},
				                {"Checagem", each ToText(_), type nullable text},
				                {"ChecagemAdiantamento", each ToText(_), type nullable text}
				            }
				        ),
				
				    #"Converted Types" =
				        Table.TransformColumns(
				            #"Text Cleaned",
				            {
				                {"DataRequisicao", each ToDate(_), type nullable date},
				                {"DataAdiantamento", each ToDate(_), type nullable date},
				                {"DataAutorizacaoDespesa", each ToDate(_), type nullable date},
				                {"Fator", each ToNumber(_), type nullable number},
				                {"ValorTabelado", each ToNumber(_), type nullable number},
				                {"ValorArbitrado", each ToNumber(_), type nullable number},
				                {"ValorAdiantado", each ToNumber(_), type nullable number},
				                {"PercentualAdiantado", each ToPercentFraction(_), type nullable number},
				                {"SaldoAReceber", each ToNumber(_), type nullable number},
				                {"SaldoFinal", each ToNumber(_), type nullable number}
				            }
				        ),
				
				    #"Filtered Rows" =
				        Table.SelectRows(
				            #"Converted Types",
				            each
				                [DataRequisicao] <> null and
				                [ValorArbitrado] <> null and
				                [PeritoNome] <> null and
				                [Comarca] <> null and
				                [Juizo] <> null and
				                [Especialidade] <> null and
				                [EspeciePericia] <> null
				        ),
				
				    #"Added PeritoNomeExibicao" = Table.AddColumn(#"Filtered Rows", "PeritoNomeExibicao", each ToDisplay([PeritoNome], "SEM PERITO"), type text),
				    #"Added JuizoExibicao" = Table.AddColumn(#"Added PeritoNomeExibicao", "JuizoExibicao", each ToDisplay([Juizo], "SEM JUÍZO"), type text),
				    #"Added ComarcaExibicao" = Table.AddColumn(#"Added JuizoExibicao", "ComarcaExibicao", each ToDisplay([Comarca], "SEM COMARCA"), type text),
				    #"Added EspecialidadeExibicao" = Table.AddColumn(#"Added ComarcaExibicao", "EspecialidadeExibicao", each ToDisplay([Especialidade], "SEM ESPECIALIDADE"), type text),
				    #"Added CpfCnpjDigits" = Table.AddColumn(#"Added EspecialidadeExibicao", "CpfCnpjDigits", each if [CpfCnpjRaw] = null then null else Text.Select([CpfCnpjRaw], {"0".."9"}), type nullable text),
				    #"Added DocValid" = Table.AddColumn(#"Added CpfCnpjDigits", "DocValid", each let d = [CpfCnpjDigits] in if d = null then null else if Text.Length(d) = 11 or Text.Length(d) = 14 then d else null, type nullable text),
				    #"Added DocFinal" = Table.AddColumn(#"Added DocValid", "DocFinal", each [DocValid], type nullable text),
				    #"Added CpfCnpjMascarado" = Table.AddColumn(#"Added DocFinal", "CpfCnpjMascarado", each MaskDoc([DocFinal]), type nullable text),
				    #"Added NomeNorm" = Table.AddColumn(#"Added CpfCnpjMascarado", "NomeNorm", each NormalizeKey([PeritoNomeExibicao]), type text),
				    #"Added PeritoKey" = Table.AddColumn(#"Added NomeNorm", "PeritoKey", each if [DocFinal] <> null and [DocFinal] <> "" then "DOC|" & [DocFinal] else "NOME|" & [NomeNorm], type text),
				    #"Added PeritoLabel" = Table.AddColumn(#"Added PeritoKey", "PeritoLabel", each if [CpfCnpjMascarado] <> null then [PeritoNomeExibicao] & " (" & [CpfCnpjMascarado] & ")" else [PeritoNomeExibicao], type text),
				    #"Added QtdDocsDistintos" = Table.AddColumn(#"Added PeritoLabel", "QtdDocsDistintos", each if [DocFinal] = null then 0 else 1, Int64.Type),
				    #"Added DocsMascaradosConcatenados" = Table.AddColumn(#"Added QtdDocsDistintos", "DocsMascaradosConcatenados", each [CpfCnpjMascarado], type nullable text),
				    #"Added NomeComDocsMultiplos" = Table.AddColumn(#"Added DocsMascaradosConcatenados", "NomeComDocsMultiplos", each "NAO", type text),
				    #"Added HasAutorizacao" = Table.AddColumn(#"Added NomeComDocsMultiplos", "HasAutorizacao", each [DataAutorizacaoDespesa] <> null, type logical),
				    #"Added HasAdiantamento" = Table.AddColumn(#"Added HasAutorizacao", "HasAdiantamento", each [DataAdiantamento] <> null or [ValorAdiantado] <> null or [PercentualAdiantado] <> null, type logical),
				    #"Added ValorAdiantadoEfetivo" = Table.AddColumn(#"Added HasAdiantamento", "ValorAdiantadoEfetivo", each if [ValorAdiantado] <> null then [ValorAdiantado] else if [PercentualAdiantado] <> null and [ValorArbitrado] <> null then [PercentualAdiantado] * [ValorArbitrado] else null, type nullable number),
				    #"Added SaldoCalculado" = Table.AddColumn(#"Added ValorAdiantadoEfetivo", "SaldoCalculado", each if [SaldoAReceber] <> null then [SaldoAReceber] else if [ValorArbitrado] <> null and [ValorAdiantadoEfetivo] <> null then [ValorArbitrado] - [ValorAdiantadoEfetivo] else [ValorArbitrado], type nullable number),
				    Today = Date.From(DateTime.LocalNow()),
				    #"Added DiasDesdeRequisicao" = Table.AddColumn(#"Added SaldoCalculado", "DiasDesdeRequisicao", each if [DataRequisicao] = null then null else Duration.Days(Today - [DataRequisicao]), Int64.Type),
				    #"Added DiasReqAteAutorizacao" = Table.AddColumn(#"Added DiasDesdeRequisicao", "DiasReqAteAutorizacao", each if [DataRequisicao] = null or [DataAutorizacaoDespesa] = null then null else Duration.Days([DataAutorizacaoDespesa] - [DataRequisicao]), Int64.Type),
				    #"Added DiasAutAteAdiantamento" = Table.AddColumn(#"Added DiasReqAteAutorizacao", "DiasAutAteAdiantamento", each if [DataAutorizacaoDespesa] = null or [DataAdiantamento] = null then null else Duration.Days([DataAdiantamento] - [DataAutorizacaoDespesa]), Int64.Type),
				    #"Added AgingFaixa" = Table.AddColumn(#"Added DiasAutAteAdiantamento", "AgingFaixa", each let d = [DiasDesdeRequisicao] in if d = null then null else if d <= 7 then "0-7" else if d <= 15 then "8-15" else if d <= 30 then "16-30" else if d <= 60 then "31-60" else if d <= 90 then "61-90" else "90+", type nullable text),
				    #"Added StatusFluxo" = Table.AddColumn(#"Added AgingFaixa", "StatusFluxo", each if [HasAutorizacao] = false then "Pendente de Autorização" else if [HasAdiantamento] = false then "Autorizado, pendente de Adiantamento" else "Com Adiantamento", type text),
				
				    FinalCols = {
				        "PeritoNome","EspeciePericia","Fator","NumeroPericia","DataRequisicao","ProcessoAdminNumero","Juizo","Comarca",
				        "ProcessoNumero","Promovente","Promovido","Especialidade","ValorTabelado","ValorArbitrado","Checagem","DataAdiantamento",
				        "ValorAdiantado","PercentualAdiantado","ChecagemAdiantamento","DataAutorizacaoDespesa","SaldoAReceber","SaldoFinal",
				        "CpfCnpjDigits","CpfCnpjMascarado","HasAutorizacao","HasAdiantamento","ValorAdiantadoEfetivo","SaldoCalculado",
				        "DiasDesdeRequisicao","AgingFaixa","DiasReqAteAutorizacao","DiasAutAteAdiantamento","StatusFluxo","PeritoNomeExibicao",
				        "JuizoExibicao","ComarcaExibicao","EspecialidadeExibicao","PeritoKey","NomeNorm","DocValid","DocFinal","QtdDocsDistintos",
				        "DocsMascaradosConcatenados","NomeComDocsMultiplos","PeritoLabel"
				    },
				    Final = Table.SelectColumns(#"Added StatusFluxo", FinalCols, MissingField.UseNull)
				in
				    Final

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

