table Orders
	isHidden
	lineageTag: 114509ab-07c9-458f-a88d-f598bcaf825a

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 683552d5-cb98-4896-bda5-7743bbedb711
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 15e4f061-a5ac-4abc-8597-105c381e70b5
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 115e7e89-9339-4bb5-b983-5938e292378d
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1034e492-d32a-4191-bf4e-6e01772480bf
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: a047fc17-17e5-455b-8936-37f501d354a5
			defaultHierarchy: LocalDateTable_50a97398-b3df-49af-898a-e7b744eebdba.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: fc651ffe-e780-46aa-b6d4-b6377089a3a1
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: fb36bc25-801c-4f89-aaa7-df3668b21488
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 7513d908-ae31-4da4-a6cb-2314550f3d3b
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: c2ee048d-1a76-4a5f-9e61-40c7290adde3
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: d0af5507-0a75-4b50-8fd6-733b6350f0f9
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: d0431d6f-df80-4be2-af21-681608531758
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b42f489f-d567-4323-995b-2e0efad41b38
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: bcddd654-6b2c-4a37-8221-932aeb3ae78a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 2c17103a-1816-4bdc-a76a-2dfb0faf366a
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 205e4023-e1c1-4592-9400-68e7a17684f0
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 968ed079-8410-40eb-a181-97993f95d5e0
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 8ccff477-7764-46d5-b562-bd0b986c76db
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: a05ebe3b-38a9-431b-8c7d-4631dfd738f1
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: f3d91ad7-cf5f-4cf1-9693-30b893546971
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: R$ #,0.00;(R$ #,0.00);R$ #,0.00
		lineageTag: 66640e3b-e755-40d8-a3d5-3bb3bc440a5a
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 3c3e055c-b798-44fc-944b-0efa1c00ed55
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 8cb1b54e-1959-4b2e-9f2c-af6538e07a65
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		formatString: R$ #,0.00;(R$ #,0.00);R$ #,0.00
		lineageTag: b4a69b04-870e-4a54-9860-a4875d9a7b68
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Shipping Cost'
		dataType: double
		lineageTag: 0d40dcf5-ed69-4905-98da-d7f947c1f27c
		summarizeBy: sum
		sourceColumn: Shipping Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Priority'
		dataType: string
		lineageTag: 7194689e-3490-41e5-80fe-db55cda69ca3
		summarizeBy: none
		sourceColumn: Order Priority

		annotation SummarizationSetBy = Automatic

	column 'State Mapa'
		dataType: string
		lineageTag: d1e5a6f2-6d8c-4f7e-a982-8fc9f1207be3
		summarizeBy: none
		sourceColumn: State Mapa

		annotation SummarizationSetBy = User

	partition Orders = m
		mode: import
		source =
				let
				    Source = FactPericias,
				    Keep = Table.SelectColumns(Source, {"NumeroPericia", "DataRequisicao", "CpfCnpjDigits", "PeritoNomeExibicao", "EspeciePericia", "JuizoExibicao", "ComarcaExibicao", "EspecialidadeExibicao", "ValorArbitrado", "SaldoCalculado", "StatusFluxo"}, MissingField.UseNull),
				    Clean = Table.TransformColumns(Keep, {
				        {"NumeroPericia", each if _ = null then null else Text.Trim(Text.From(_)), type nullable text},
				        {"CpfCnpjDigits", each if _ = null then null else Text.Trim(Text.From(_)), type nullable text},
				        {"PeritoNomeExibicao", each if _ = null or Text.Trim(Text.From(_)) = "" then "SEM PERITO" else Text.Trim(Text.From(_)), type text},
				        {"EspeciePericia", each if _ = null or Text.Trim(Text.From(_)) = "" then "SEM ESPĂCIE" else Text.Trim(Text.From(_)), type text},
				        {"JuizoExibicao", each if _ = null or Text.Trim(Text.From(_)) = "" then "SEM JUĂZO" else Text.Trim(Text.From(_)), type text},
				        {"ComarcaExibicao", each if _ = null or Text.Trim(Text.From(_)) = "" then "SEM COMARCA" else Text.Trim(Text.From(_)), type text},
				        {"EspecialidadeExibicao", each if _ = null or Text.Trim(Text.From(_)) = "" then "SEM ESPECIALIDADE" else Text.Trim(Text.From(_)), type text}
				    }),
				    NormalizeComarcaMapa = (value as any) as nullable text =>
				        let
				            StripAccents = (textValue as nullable text) as nullable text =>
				                if textValue = null then
				                    null
				                else
				                    let
				                        Replacements = {
				                            {"Ă", "A"}, {"Ă", "A"}, {"Ă", "A"}, {"Ă", "A"}, {"Ă", "A"},
				                            {"ĂĄ", "a"}, {"Ă ", "a"}, {"Ăą", "a"}, {"ĂŁ", "a"}, {"Ă€", "a"},
				                            {"Ă", "E"}, {"Ă", "E"}, {"Ă", "E"}, {"Ă", "E"},
				                            {"Ă©", "e"}, {"Ăš", "e"}, {"ĂȘ", "e"}, {"Ă«", "e"},
				                            {"Ă", "I"}, {"Ă", "I"}, {"Ă", "I"}, {"Ă", "I"},
				                            {"Ă­", "i"}, {"ĂŹ", "i"}, {"Ăź", "i"}, {"ĂŻ", "i"},
				                            {"Ă", "O"}, {"Ă", "O"}, {"Ă", "O"}, {"Ă", "O"}, {"Ă", "O"},
				                            {"Ăł", "o"}, {"ĂČ", "o"}, {"ĂŽ", "o"}, {"Ă”", "o"}, {"Ă¶", "o"},
				                            {"Ă", "U"}, {"Ă", "U"}, {"Ă", "U"}, {"Ă", "U"},
				                            {"Ăș", "u"}, {"Ăč", "u"}, {"Ă»", "u"}, {"ĂŒ", "u"},
				                            {"Ă", "C"}, {"Ă§", "c"},
				                            {"Ă", "N"}, {"Ă±", "n"}
				                        },
				                        Stripped = List.Accumulate(Replacements, textValue, (state as text, pair as list) => Text.Replace(state, pair{0}, pair{1}))
				                    in
				                        Stripped,
				            NormalizeKey = (textValue as nullable text) as nullable text =>
				                if textValue = null then
				                    null
				                else
				                    let
				                        Upper = Text.Upper(StripAccents(Text.Trim(textValue))),
				                        KeepChars = Text.Select(Upper, List.Combine({{"A".."Z"}, {"0".."9"}, {" "}})),
				                        Parts = List.Select(Text.Split(KeepChars, " "), each _ <> ""),
				                        Key = if List.Count(Parts) = 0 then null else Text.Combine(Parts, " ")
				                    in
				                        Key,
				            OfficialComarcaByKey = [
				                #"AGUA BRANCA" = "Ăgua Branca",
				                #"ALAGOA GRANDE" = "Alagoa Grande",
				                #"ALAGOA NOVA" = "Alagoa Nova",
				                #"ALAGOINHA" = "Alagoinha",
				                #"ALHANDRA" = "Alhandra",
				                #"ARACAGI" = "AraĂ§agi",
				                #"ARARA" = "Arara",
				                #"ARARUNA" = "Araruna",
				                #"AREIA" = "Areia",
				                #"AROEIRAS" = "Aroeiras",
				                #"BANANEIRAS" = "Bananeiras",
				                #"BARRA DE SANTA ROSA" = "Barra de Santa Rosa",
				                #"BAYEUX" = "Bayeux",
				                #"BELEM" = "BelĂ©m",
				                #"BONITO DE SANTA FE" = "Bonito de Santa FĂ©",
				                #"BOQUEIRAO" = "BoqueirĂŁo",
				                #"BREJO DO CRUZ" = "Brejo do Cruz",
				                #"CAAPORA" = "CaaporĂŁ",
				                #"CABACEIRAS" = "Cabaceiras",
				                #"CABEDELO" = "Cabedelo",
				                #"CACIMBA DE DENTRO" = "Cacimba de Dentro",
				                #"CAICARA" = "CaiĂ§ara",
				                #"CAJAZEIRAS" = "Cajazeiras",
				                #"CAMPINA GRANDE" = "Campina Grande",
				                #"CATOLE DO ROCHA" = "CatolĂ© do Rocha",
				                #"CONCEICAO" = "ConceiĂ§ĂŁo",
				                #"CONDE" = "Conde",
				                #"COREMAS" = "Coremas",
				                #"CRUZ DO ESPIRITO SANTO" = "Cruz do EspĂ­rito Santo",
				                #"CUITE" = "CuitĂ©",
				                #"ESPERANCA" = "EsperanĂ§a",
				                #"GUARABIRA" = "Guarabira",
				                #"GURINHEM" = "GurinhĂ©m",
				                #"INGA" = "IngĂĄ",
				                #"ITABAIANA" = "Itabaiana",
				                #"ITAPORANGA" = "Itaporanga",
				                #"JACARAU" = "JacaraĂș",
				                #"JOAO PESSOA" = "JoĂŁo Pessoa",
				                #"JUAZEIRINHO" = "Juazeirinho",
				                #"LUCENA" = "Lucena",
				                #"MALTA" = "Malta",
				                #"MAMANGUAPE" = "Mamanguape",
				                #"MARI" = "Mari",
				                #"MONTEIRO" = "Monteiro",
				                #"PATOS" = "Patos",
				                #"PAULISTA" = "Paulista",
				                #"PEDRAS DE FOGO" = "Pedras de Fogo",
				                #"PIANCO" = "PiancĂł",
				                #"PICUI" = "PicuĂ­",
				                #"PILAR" = "Pilar",
				                #"PILOES" = "PilĂ”es",
				                #"PIRPIRITUBA" = "Pirpirituba",
				                #"POCINHOS" = "Pocinhos",
				                #"POMBAL" = "Pombal",
				                #"PRATA" = "Prata",
				                #"PRINCESA ISABEL" = "Princesa Isabel",
				                #"QUEIMADAS" = "Queimadas",
				                #"REMIGIO" = "RemĂ­gio",
				                #"RIO TINTO" = "Rio Tinto",
				                #"SANTA LUZIA" = "Santa Luzia",
				                #"SANTA RITA" = "Santa Rita",
				                #"SANTANA DOS GARROTES" = "Santana dos Garrotes",
				                #"SAO BENTO" = "SĂŁo Bento",
				                #"SAO JOAO DO CARIRI" = "SĂŁo JoĂŁo do Cariri",
				                #"SAO JOAO DO RIO DO PEIXE" = "SĂŁo JoĂŁo do Rio do Peixe",
				                #"SAO JOSE DA LAGOA TAPADA" = "SĂŁo JosĂ© da Lagoa Tapada",
				                #"SAO JOSE DE PIRANHAS" = "SĂŁo JosĂ© de Piranhas",
				                #"SAO MAMEDE" = "SĂŁo Mamede",
				                #"SAPE" = "SapĂ©",
				                #"SERRA BRANCA" = "Serra Branca",
				                #"SERRARIA" = "Serraria",
				                #"SOLANEA" = "SolĂąnea",
				                #"SOLEDADE" = "Soledade",
				                #"SOUSA" = "Sousa",
				                #"SUME" = "SumĂ©",
				                #"TAPEROA" = "TaperoĂĄ",
				                #"TEIXEIRA" = "Teixeira",
				                #"UIRAUNA" = "UiraĂșna",
				                #"UMBUZEIRO" = "Umbuzeiro"
				            ],
				            AliasToComarcaKey = [
				                #"BAYEUX E SANTA RITA" = "SANTA RITA",
				                #"PRINCESA ISABEL E AGUA BRANCA" = "PRINCESA ISABEL",
				                #"LITORAL SUL" = "ALHANDRA",
				                #"COMARCA INT PRIC ISABEL E AGUA BRANCA" = "PRINCESA ISABEL",
				                #"COMARCAS INTEGRADAS DO LITORAL SUL" = "ALHANDRA",
				                #"SAO JOSE DE LAGOA TAPADA" = "SAO JOSE DA LAGOA TAPADA"
				            ],
				            Base = if value = null then null else Text.Trim(Text.From(value)),
				            UpperBase = if Base = null then null else Text.Upper(Base),
				            WithoutPrefix =
				                if UpperBase = null then null
				                else if Text.StartsWith(UpperBase, "COMARCA INTEGRADA DE ") then Text.Trim(Text.Range(Base, Text.Length("Comarca Integrada de ")))
				                else if Text.StartsWith(UpperBase, "COMARCA INTEGRADA DA ") then Text.Trim(Text.Range(Base, Text.Length("Comarca Integrada da ")))
				                else if Text.StartsWith(UpperBase, "COMARCA INTEGRADA DO ") then Text.Trim(Text.Range(Base, Text.Length("Comarca Integrada do ")))
				                else if Text.StartsWith(UpperBase, "COMARCA DE ") then Text.Trim(Text.Range(Base, Text.Length("Comarca de ")))
				                else if Text.StartsWith(UpperBase, "COMARCA DA ") then Text.Trim(Text.Range(Base, Text.Length("Comarca da ")))
				                else if Text.StartsWith(UpperBase, "COMARCA DO ") then Text.Trim(Text.Range(Base, Text.Length("Comarca do ")))
				                else Base,
				            WithoutUf1 = if WithoutPrefix = null then null else Text.Replace(WithoutPrefix, "/PB", ""),
				            WithoutUf2 = if WithoutUf1 = null then null else Text.Replace(WithoutUf1, "- PB", ""),
				            WithoutUf3 = if WithoutUf2 = null then null else Text.Replace(WithoutUf2, "(PB)", ""),
				            KeyRaw = NormalizeKey(WithoutUf3),
				            KeyFinal = if KeyRaw <> null and Record.HasFields(AliasToComarcaKey, KeyRaw) then Record.Field(AliasToComarcaKey, KeyRaw) else KeyRaw,
				            Canonical = if KeyFinal = null then null else Record.FieldOrDefault(OfficialComarcaByKey, KeyFinal, null)
				        in
				            Canonical,
				    Filtered = Table.SelectRows(Clean, each [DataRequisicao] <> null and [ValorArbitrado] <> null),
				    #"Added Index" = Table.AddIndexColumn(Filtered, "Row ID", 1, 1, Int64.Type),
				    #"Added Order ID" = Table.AddColumn(#"Added Index", "Order ID", each if [NumeroPericia] <> null and [NumeroPericia] <> "" then [NumeroPericia] else Text.From([#"Row ID"]), type text),
				    #"Added Order Date" = Table.AddColumn(#"Added Order ID", "Order Date", each Date.From([DataRequisicao]), type date),
				    #"Added Ship Date" = Table.AddColumn(#"Added Order Date", "Ship Date", each Date.From([DataRequisicao]), type date),
				    #"Added Ship Mode" = Table.AddColumn(#"Added Ship Date", "Ship Mode", each let v = [ValorArbitrado] in if v = null then null else if v < 300 then "AtĂ© R$ 300" else if v < 370 then "R$ 300 - 369" else if v < 450 then "R$ 370 - 449" else if v < 1000 then "R$ 450 - 999" else "R$ 1.000+", type text),
				    #"Added Customer ID" = Table.AddColumn(#"Added Ship Mode", "Customer ID", each [CpfCnpjDigits], type text),
				    #"Added Customer Name" = Table.AddColumn(#"Added Customer ID", "Customer Name", each [PeritoNomeExibicao], type text),
				    #"Added Segment" = Table.AddColumn(#"Added Customer Name", "Segment", each [EspecialidadeExibicao], type text),
				    #"Added Postal Code" = Table.AddColumn(#"Added Segment", "Postal Code", each null, Int64.Type),
				    #"Added City" = Table.AddColumn(#"Added Postal Code", "City", each [JuizoExibicao], type text),
				    #"Added State" = Table.AddColumn(#"Added City", "State", each [ComarcaExibicao], type text),
				    #"Added State Mapa" = Table.AddColumn(#"Added State", "State Mapa", each NormalizeComarcaMapa([ComarcaExibicao]), type nullable text),
				    #"Added Country" = Table.AddColumn(#"Added State Mapa", "Country", each "Brasil", type text),
				    #"Added Region" = Table.AddColumn(#"Added Country", "Region", each [ComarcaExibicao], type text),
				    #"Added Market" = Table.AddColumn(#"Added Region", "Market", each "TJPB", type text),
				    #"Added Product ID" = Table.AddColumn(#"Added Market", "Product ID", each [NumeroPericia], type text),
				    #"Added Category" = Table.AddColumn(#"Added Product ID", "Category", each [EspecialidadeExibicao], type text),
				    #"Added Sub-Category" = Table.AddColumn(#"Added Category", "Sub-Category", each [JuizoExibicao], type text),
				    #"Added Product Name" = Table.AddColumn(#"Added Sub-Category", "Product Name", each [PeritoNomeExibicao], type text),
				    #"Added Sales" = Table.AddColumn(#"Added Product Name", "Sales", each Number.From([ValorArbitrado]), type number),
				    #"Added Quantity" = Table.AddColumn(#"Added Sales", "Quantity", each 1, Int64.Type),
				    #"Added Discount" = Table.AddColumn(#"Added Quantity", "Discount", each 0, type number),
				    #"Added Profit" = Table.AddColumn(#"Added Discount", "Profit", each Number.From([SaldoCalculado]), type number),
				    #"Added Shipping Cost" = Table.AddColumn(#"Added Profit", "Shipping Cost", each null, type number),
				    #"Added Order Priority" = Table.AddColumn(#"Added Shipping Cost", "Order Priority", each [StatusFluxo], type text),
				    #"Selected Columns" = Table.SelectColumns(#"Added Order Priority", {"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Postal Code", "City", "State", "State Mapa", "Country", "Region", "Market", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit", "Shipping Cost", "Order Priority"})
				in
				    #"Selected Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

